"" Ensure that <> notation works for the mappings that follow
set nocompatible

"" Scroll only one line for mouse wheel events to get smooth scrolling on touch screens
"map <ScrollWheelUp> <C-Y>
"imap <ScrollWheelUp> <C-X><C-Y>
"map <ScrollWheelDown> <C-E>
"imap <ScrollWheelDown> <C-X><C-E>

"" As of version 8, vim enables the mouse by default - but only if no ~/.vimrc
"" is found. Enable that unconditionally for Termux as it's useful with touch:
set mouse=a

" sensible.vim - Defaults everyone can agree on
" Maintainer:   Tim Pope <http://tpo.pe/>
" Version:      1.2

"if exists('g:loaded_sensible') || &compatible 
"	finish
"else
"  let g:loaded_sensible = 'yes'
"endif

"if has('autocmd')
"  filetype plugin indent on
"endif
"if has('syntax') && !exists('g:syntax_on')
"  syntax enable
"endif

" Use :help 'option' to see the documentation for the given option.

set autoindent
set backspace=indent,eol,start
set complete-=i
set smarttab

set nrformats-=octal

"if !has('nvim') && &ttimeoutlen == -1
"  set ttimeout
"  set ttimeoutlen=100
"endif

"set incsearch
" Use <C-L> to clear the highlighting of :set hlsearch.
"if maparg('<C-L>', 'n') ==# ''
"  nnoremap <silent> <C-L> :nohlsearch<C-R>=has('diff')?'<Bar>diffupdate':''<CR><CR><C-L>
"endif

"set laststatus=2
"set ruler
"set wildmenu

"if !&scrolloff
"  set scrolloff=1
"endif
"if !&sidescrolloff
"  set sidescrolloff=5
"endif
"set display+=lastline

"if &encoding ==# 'latin1' && has('gui_running')
"  set encoding=utf-8
"endif

"if &listchars ==# 'eol:$'
"  set listchars=tab:>\ ,trail:-,extends:>,precedes:<,nbsp:+
"endif

"if v:version > 703 || v:version == 703 && has("patch541")
"  set formatoptions+=j " Delete comment character when joining commented lines
"endif

"if has('path_extra')
"  setglobal tags-=./tags tags-=./tags; tags^=./tags;
"endif

"if &shell =~# 'fish$' && (v:version < 704 || v:version == 704 && !has('patch276'))
"  set shell=/usr/bin/env\ bash
"endif

"set autoread

"if &history < 1000
"  set history=1000
"endif
"if &tabpagemax < 50
"  set tabpagemax=50
"endif
"if !empty(&viminfo)
"  set viminfo^=!
"endif
"set sessionoptions-=options

" Allow color schemes to do bright colors without forcing bold.
"if &t_Co == 8 && $TERM !~# '^linux\|^Eterm'
"  set t_Co=16
"endif

" Load matchit.vim, but only if the user hasn't installed a newer version.
"if !exists('g:loaded_matchit') && findfile('~/.vim/plugin/matchit.vim', &rtp) ==# ''
"  runtime! macros/matchit.vim
"endif

"inoremap <C-U> <C-G>u<C-U>

" vim:set ft=vim et sw=2:

" exit to normal mode with 'jj'
"inoremap jj <ESC>


"~~~~~config by black ugolnik~~~~
                                                                        
"" number stroke:
"set number
"" number tekushey stroke:
"set relativenumber
"" auto otstup:
set autoindent
"" tab value:
set tabstop=4
"" line:
set shiftwidth=4
"" interpretation tab
set smarttab
"" tab value vo vstavke:
set softtabstop=4
"" scroll no button
set scrolloff=7
"" mouse:
set mouse=a


"~~~~~~~~~~~~~~~~~~~~list plugins
call plug#begin('~/.vim/plugged')


"bootom stroke
Plug 'https://github.com/vim-airline/vim-airline'

"airline theme (+dobavit'b v vimrc: let g:airline_theme='simple'(na3vanyE)
Plug 'https://github.com/vim-airline/vim-airline-themes'

"menu files in left
Plug 'https://github.com/preservim/nerdtree'

"css color
Plug 'https://github.com/ap/vim-css-color'

"color thems vim
Plug 'https://github.com/rafi/awesome-vim-colorschemes'

"terminal(:Terminal <comand/file> :help Terminal)
Plug 'https://github.com/tc50cal/vim-terminal'

"tagbar in text(v vimrc po F8: nmap <F8> :TagbarToggle<CR>)
Plug 'https://github.com/preservim/tagbar'

"vim icons(posledniy)
Plug 'https://github.com/ryanoasis/vim-devicons'

"podskazki code( ---- ne podklucheno!!!!!!)
"Plug 'https://github.com/neoclide/coc.nvim'

"dopolnenye code (mnogo ect)
"Plug 'https://github.com/ycm-core/YouCompleteMe'

"tagbar po text'u
nmap <F8> :TagbarToggle<CR>
"open/close spisok files
nnoremap <C-n> :NERDTree<CR>
nnoremap <C-t> :NERDTreeToggle<CR>
"colors them
"source /data/data/com.termux/files/home/.vim/plugged/awesome-vim-colorschemes/colors/torte.vim
source ~/.vim/plugged/awesome-vim-colorschemes/colors/molokai.vim
set encoding=UTF-8
"interpretation module(podskazki)
set completeopt-=preview



call plug#end()
"~~~~~~~~~~~~~~~~~~~~~~~~~


